### ISSUE TITLE
Unable to sort search results when using MySQL

### ISSUE THREAD

**Issue by IanMMarshall** [hapifhir/hapi-fhir#2260]
Steps to duplicate:
1. Set up a simple HAPI FHIR JPA Server connecting to a MySQL server database. E.g. Build the JPAServer Starter project using the HAPI FHIR 5.3.0-Snapshot and include configuration similar to the following in the application.yaml:

```
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/samplehapi?serverTimezone=Canada/Eastern'
    username: samplehapi
    password: HapiFHIR
    driverClassName: com.mysql.jdbc.Driver
    max-active: 15
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.lucenesearchmappingfactory
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexbase: target/lucenefiles
      hibernate.search.lucene_version: lucene_current

  batch:
    job:
      enabled: false
```

2. POST one or more Observation resources to the server.
3. Execute a simple search for Observation resources, sorting by lastUpdated, e.g.:

```
GET /Observation/?_sort=_lastUpdated
``` 

Expected behaviour: Should get a Bundle of Observation resources ordered by lastUpdated date/time.

Actual behaviour: Get an exception related to invalid SQL syntax, e.g.:

```json
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULLS LAST limit 500' at line 1</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULLS LAST limit 500' at line 1"
    }
  ]
}
```

Issue is likely related to known limitations of certain databases relating to the `NULLS LAST` option in `ORDER BY` clause (see article here for more information https://dba-presents.com/index.php/databases/sql-server/36-order-by-and-nulls-last-in-sql-server).
