### ISSUE TITLE
Wrong column type encountered in column params_json_lob in table bt2_job_instance

### ISSUE THREAD

**Issue by egaga** [hapifhir/hapi-fhir#4369]
The 6.2.2 HAPI FHIR application does not work with a column that is in the database (fails on Hibernate schema validation).
This might be due to migration tool producing a column type for Postgres database that is not expected by the application, or another suspect is that if the original database has been created with Hibernate schema auto-update (I don't know).

In any case, the application worked with 5.7.0 but doesn't with 6.2.2 after migrating successfully with the HAPI FHIR migration tool.

HAPI version:
- before: 5.7.0
- new: 6.2.2

```sh
hapi-fhir-cli migrate-database \
  -u "jdbc:postgresql://localhost:$PORT/ecosystem-api" \
  --username="$USERNAME" --password="$PASSWORD" \
  --driver=POSTGRES_9_4
```

This gives _successful_ output with relevant log entry that is probably problematic:
> 2022-12-05 15:56:04.723 [main] INFO  c.u.f.j.m.t.BaseTask 6.0.0.20220227.1: SQL "CREATE TABLE BT2_JOB_INSTANCE ( ID varchar(100)  not null, CREATE_TIME timestamp  not null, START_TIME timestamp , END_TIME timestamp , DEFINITION_ID varchar(100)  not null, DEFINITION_VER int4  not null, STAT varchar(20)  not null, JOB_CANCELLED boolean  not null, PARAMS_JSON varchar(2000) , **PARAMS_JSON_LOB text** , CMB_RECS_PROCESSED int4 , CMB_RECS_PER_SEC float8 , TOT_ELAPSED_MILLIS int4 , WORK_CHUNKS_PURGED boolean  not null, PROGRESS_PCT float8 , ERROR_MSG varchar(500) , ERROR_COUNT int4 , EST_REMAINING varchar(100) ,  PRIMARY KEY (ID) ) " returned 0

When running HAPI FHIR 6.2.
>  Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [params_json_lob] in table [bt2_job_instance]; found [text (Types#VARCHAR)], but expecting [oid (Types#CLOB)]

Possibly relevant Hibernate properties:
```yaml
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
        hbm2ddl:
          auto: validate
```

Postgres is version 11.

If the same migration command is run against an empty database, then the migration tool creates different column type and the HAPI FHIR server starts successfully:

```sh
2022-12-14 13:12:04.252 [main] INFO  c.u.f.j.m.t.BaseTask 3.3.0.20180115.0: SQL 
    create table BT2_JOB_INSTANCE (
        ...removed other columns...
        PARAMS_JSON_LOB oid,
    )" returned 0
```
