### ISSUE TITLE
Add SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT to docker-compose.yml

### ISSUE THREAD

**Issue by Robinyo** [hapifhir/hapi-fhir#6547]
**Describe the bug**
SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT not set in docker-compose.yml

**To Reproduce**
Steps to reproduce the behaviour:
```
docker compose up
```

**Expected behaviour**
Services startup without issue.

For example:

```
services:
  hapi-fhir-jpaserver:
    build: .
    container_name: hapi-fhir-jpaserver
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
```

**Environment (please complete the following information):**
HAPI FHIR Version: HAPI FHIR 7.6.0 REST Server (FHIR Server; FHIR 4.0.1/R4)
OS: MacOS Sequoia 15.1.1 (Docker Desktop v.4.36.0)
Browser: Chrome
