### ISSUE TITLE
Add extra details to LastN documentation describing proper lastN configuration

### ISSUE THREAD

**Issue by nazeem-soeltan** [hapifhir/hapi-fhir#7090]
**Describe the issue**
Section 5.10.4 Deployment and Configuration of the $LastN Operation can be improved. I was trying out the LastN functionality by enabling the flag and setting the elastic configuration. However, in order for LastN to work properly, one must make sure that the following is also set:

```
spring:
  jpa:
    properties:
      hibernate.search.enabled: true
      hibernate.search.backend.type: elasticsearch
```

and

```
hapi:
  fhir:
    advanced-lucene-indexing: true
```

I would advise to incorporate it. Or if there is a doc repo I can add it if needed.

**Environment (please complete the following information):**

- HAPI FHIR Version: R4 / DSTU3
- OS: MacOS 15.5
- Browser: Firefox

**Additional context**
